# SHAP Values - Companion Notebook 2: Computing SHAP Values by Hand

This notebook accompanies Sections 2, 3, and 4 of `lecture_notes/17_shap_values.pdf`.

Goals:
- implement the interventional definition of $h(x_S)$;
- compute marginal contributions $\Delta_i^S$;
- reproduce the full numerical example from the notes;
- see how interactions are shared across features.

In [1]:
import itertools
import math
import numpy as np
import pandas as pd

feature_names = ["x1", "x2"]
F = tuple(feature_names)
background = pd.DataFrame(
    [(0, 0), (0, 1), (1, 0), (1, 1)],
    columns=feature_names,
)
x = pd.Series({"x1": 1, "x2": 1})
background

   x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

## 1. Interventional $h(x_S)$

The model always receives a complete input. To evaluate $h(x_S)$, we:

1. keep the features in $S$ fixed to their values in the target instance $x$;
2. replace features outside $S$ with values from each background row;
3. average the resulting predictions.

In [2]:
def powerset(items):
    items = tuple(items)
    for r in range(len(items) + 1):
        yield from itertools.combinations(items, r)


def interventional_value(model, known_features, x, background):
    rows = background.copy()
    for feature in known_features:
        rows[feature] = x[feature]
    return float(np.mean(model(rows)))


def shap_weight(n_features, subset_size):
    return (
        math.factorial(subset_size)
        * math.factorial(n_features - subset_size - 1)
        / math.factorial(n_features)
    )


def exact_shap_values(model, x, background):
    features = tuple(background.columns)
    phi = {}
    rows = []

    for feature in features:
        others = tuple(f for f in features if f != feature)
        value = 0.0
        for S in powerset(others):
            S = tuple(S)
            with_feature = tuple(sorted(S + (feature,)))
            without_feature = S
            delta = (
                interventional_value(model, with_feature, x, background)
                - interventional_value(model, without_feature, x, background)
            )
            weight = shap_weight(len(features), len(S))
            value += weight * delta
            rows.append(
                {
                    "feature": feature,
                    "S": "{" + ", ".join(S) + "}",
                    "h(x_S)": interventional_value(model, without_feature, x, background),
                    "h(x_S_with_i)": interventional_value(model, with_feature, x, background),
                    "delta": delta,
                    "weight": weight,
                    "weighted_delta": weight * delta,
                }
            )
        phi[feature] = value

    return pd.Series(phi), pd.DataFrame(rows)

## 2. Additive model from the lecture notes

First use the additive model $h(x_1,x_2)=3x_1+5x_2$.

In [3]:
def additive_model(X):
    return 3 * X["x1"] + 5 * X["x2"]

phi_additive, table_additive = exact_shap_values(additive_model, x, background)
phi_0_additive = interventional_value(additive_model, (), x, background)
pred_additive = float(additive_model(pd.DataFrame([x]))[0])

display(table_additive)
print("phi_0:", phi_0_additive)
print("phi:")
print(phi_additive)
print("phi_0 + sum(phi_i):", phi_0_additive + phi_additive.sum())
print("h(x):", pred_additive)

  feature     S  h(x_S)  h(x_S_with_i)  delta  weight  weighted_delta
0      x1    {}     4.0            5.5    1.5     0.5            0.75
1      x1  {x2}     6.5            8.0    1.5     0.5            0.75
2      x2    {}     4.0            6.5    2.5     0.5            1.25
3      x2  {x1}     5.5            8.0    2.5     0.5            1.25

phi_0: 4.0
phi:
x1    1.5
x2    2.5
dtype: float64
phi_0 + sum(phi_i): 8.0
h(x): 8.0

## 3. Nonlinear context-dependence example

Now use the model from Section 3.2:

$$h(x_1,x_2)=x_1x_2.$$

The contribution of $x_1$ depends on whether $x_2$ is already known.

In [4]:
def interaction_model(X):
    return X["x1"] * X["x2"]

phi_interaction, table_interaction = exact_shap_values(interaction_model, x, background)
phi_0_interaction = interventional_value(interaction_model, (), x, background)
pred_interaction = float(interaction_model(pd.DataFrame([x]))[0])

display(table_interaction)
print("phi_0:", phi_0_interaction)
print("phi:")
print(phi_interaction)
print("phi_0 + sum(phi_i):", phi_0_interaction + phi_interaction.sum())
print("h(x):", pred_interaction)

  feature     S  h(x_S)  h(x_S_with_i)  delta  weight  weighted_delta
0      x1    {}    0.25            0.5   0.25     0.5           0.125
1      x1  {x2}    0.50            1.0   0.50     0.5           0.250
2      x2    {}    0.25            0.5   0.25     0.5           0.125
3      x2  {x1}    0.50            1.0   0.50     0.5           0.250

phi_0: 0.25
phi:
x1    0.375
x2    0.375
dtype: float64
phi_0 + sum(phi_i): 1.0
h(x): 1.0

## 4. What changed?

For the additive model, each feature has the same marginal contribution in every context. For the interaction model, the marginal contribution changes with the coalition $S$.

SHAP handles this by averaging over all possible feature orderings. That is why the interaction effect is split across the features instead of being assigned entirely to one of them.

In [5]:
comparison = pd.DataFrame(
    {
        "additive_phi": phi_additive,
        "interaction_phi": phi_interaction,
    }
)
comparison.loc["baseline", :] = [phi_0_additive, phi_0_interaction]
comparison.loc["prediction", :] = [pred_additive, pred_interaction]
comparison

            additive_phi  interaction_phi
x1                   1.5            0.375
x2                   2.5            0.375
baseline             4.0            0.250
prediction           8.0            1.000